'use client';

import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';

type Discount = { id: string; code: string; type: string; scope: string; value: number; isActive: boolean; isAutomatic: boolean };

export default function DiscountsPage() {
  const [discounts, setDiscounts] = useState<Discount[]>([]);
  const [form, setForm] = useState({ code: '', type: 'PORCENTAJE', value: '', scope: 'CARRITO' });
  const [error, setError] = useState('');
  const load = async () => { const response = await fetch('/api/admin/discounts', { cache: 'no-store' }); const data = await response.json(); if (response.ok) setDiscounts(data.discounts.map((item: Discount) => ({ ...item, value: Number(item.value) }))); else setError(data.error || 'No se pudieron cargar los descuentos'); };
  useEffect(() => { void load(); }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch('/api/admin/discounts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, code: form.code.toUpperCase(), value: Number(form.value), startDate: new Date().toISOString(), endDate: new Date(Date.now() + 31536000000).toISOString(), applicableCategories: [], applicableProducts: [], isActive: true, isAutomatic: false }) }); const data = await response.json(); if (!response.ok) setError(data.error || 'No se pudo crear el descuento'); else { setForm({ ...form, code: '', value: '' }); void load(); } };
  const toggle = async (discount: Discount) => { await fetch(`/api/admin/discounts/${discount.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ isActive: !discount.isActive }) }); void load(); };
  return <div className="space-y-6"><h1 className="font-serif text-3xl font-bold text-coffee-900">Descuentos</h1><form onSubmit={create} className="flex flex-wrap gap-3 rounded-xl border border-cream-200 bg-white p-4"><input className="rounded-md border border-cream-300 px-3 py-2" placeholder="Código" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} required /><select className="rounded-md border border-cream-300 px-3 py-2" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="PORCENTAJE">Porcentaje</option><option value="VALOR_FIJO">Valor fijo</option></select><input className="w-28 rounded-md border border-cream-300 px-3 py-2" type="number" min="1" placeholder="Valor" value={form.value} onChange={(e) => setForm({ ...form, value: e.target.value })} required /><select className="rounded-md border border-cream-300 px-3 py-2" value={form.scope} onChange={(e) => setForm({ ...form, scope: e.target.value })}><option value="CARRITO">Carrito</option><option value="PRODUCTOS">Productos</option><option value="CATEGORIAS">Categorías</option></select><Button type="submit">Crear descuento</Button></form>{error && <p className="text-sm text-red-600">{error}</p>}<div className="rounded-xl border border-cream-200 bg-white p-4">{discounts.length === 0 ? <p className="text-secondary-600">No hay descuentos registrados.</p> : discounts.map((discount) => <div key={discount.id} className="flex items-center justify-between border-b border-cream-200 p-3"><span>{discount.code} · {discount.scope} · {discount.type === 'PORCENTAJE' ? `${discount.value}%` : `$${discount.value.toLocaleString('es-CO')}`}</span><Button variant="outline" size="sm" onClick={() => void toggle(discount)}>{discount.isActive ? 'Desactivar' : 'Activar'}</Button></div>)}</div></div>;
}
